name: joinable_env
channels:
  - pytorch
  - rusty1s
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - pytorch=2.2
  - cudatoolkit=12.1
  - torchvision=0.17.2
  - pytorch-lightning=2.2.5
  - torchmetrics=1.4.0
  - matplotlib
  - tqdm
  - pytorch-geometric=2.5.2
  - networkx
  - scipy
  - igl
  - meshplot
  - pip:
    - pysdf
    - trimesh[easy]    